### ISSUE TITLE
Incompatible with bugsnag

### ISSUE THREAD

**Issue by SleeplessByte** [alchapone/polymer-rails#10]
`gem 'bugsnag'` together with the polymer-rails gem will cause this error:

```
undefined method `html_import_tag' for #<#<Class:OBJECTID>:ANOTHER_OBJECTID>
```

I know the [bugsnag/bugsnag-ruby](https://github.com/bugsnag/bugsnag-ruby) gem injects scripts into the layouts (to enable the gem), so maybe y'all are overwriting some function? Instead of extending it?

**Comment by alexvbush** [comment]
I'm getting the same issue with 1.1.0

**Comment by alexvbush** [comment]
I have a brand new rails 4.2 app with no extra gems. After I've done my polymer gem setup and inerted `html_import_tag`  I got `undefined method `html_import_tag' for #<#<Class:OBJECTID>:ANOTHER_OBJECTID>`

**Comment by SleeplessByte** [comment]
Might this be a platform specific issue?

**Comment by alchapone** [comment]
Possible solution in the end of #63 ;)

**Comment by nanowang** [comment]
I'm using Bugsnag and everything looks fine to me.
