### ISSUE TITLE
uninitialized constant Sprockets::DirectiveProcessor

### ISSUE THREAD

**Issue by fabianrios** [alchapone/polymer-rails#29]
if I try to install 
rails g polymer:install
I got this error
.rvm/gems/ruby-2.0.0-p451/gems/polymer-rails-0.1.9/lib/polymer-rails/processors/directive_processor.rb:3:in `module:Rails': uninitialized constant Sprockets::DirectiveProcessor (NameError)

**Comment by duykhoa** [comment]
**UPDATE** for the newer version, you can run `bundle update polymer-rails`, it'll automatically choose the older version for `sprocket` gem. Current version of sprocket is `3.2.0`, but polymer-rails use `2.12.4`

:100:
