### ISSUE TITLE
Binding on checkbox doesn't work

### ISSUE THREAD

**Issue by lloeki** [alchapone/polymer-rails#31]
We're test-driving polymer-rails on a few of our applications (one in rails 3.2 and one in rails 4.1) and it seems there's an issue with binding on checkboxes ([demo](http://jsbin.com/mujuwi/edit?html,output)). I'm not too sure but it appears like no event fires and what should be updated isn't. No error in the console.

To reproduce this in a clean environment, I simply hacked this into your [polymer-rails-example](https://github.com/alchapone/polymer-rails-example) app:

```html
<polymer-element name="my-navigation">
  <template>
    <div>
      <label>
        <template if="{{checked}}">Uncheck</template>
        <template if="{{!checked}}">Check</template>
      </label><br>
      <input type="checkbox" checked="{{checked}}">
    </div>
  </template>
  <script>
  Polymer({
    checked: false
  });
  </script>
</polymer-element>
```

Since I have another app in Go that uses polymer 0.5.1 (via bower) I added the same code as above, and the binding works there. Therefore I can only conclude that *something* in polymer-rails somehow gets in the way and prevents the binding from working, though I have no clue what.

Can you reproduce this?

**Comment by alchapone** [comment]
I know, it's been a long time. But I've got that solved https://github.com/alchapone/polymer-rails/commit/d1961c79d6f5b8a940d9a4e291827fa057c69514 master branch currently supports checkbox bindings
