### ISSUE TITLE
Use with JRuby

### ISSUE THREAD

**Issue by donv** [alchapone/polymer-rails#32]
Hi!

is there a way to use polymer-rails with JRuby?  It seems there is a dependency on nokogumbo which tries to compile a C extension.

What is the C extension for?

**Comment by alchapone** [comment]
polymer-rails uses [gumbo](https://github.com/google/gumbo-parser) parser via [nokogumbo](https://github.com/rubys/nokogumbo/) gem to process component html see https://github.com/alchapone/polymer-rails/issues/15 for details
