### ISSUE TITLE
Tags embed wrong

### ISSUE THREAD

**Issue by jdsampayo** [alchapone/polymer-rails#34]
I'm trying to replicate the topeka project, but the tags are rendering wrong, for example this part:

    <polymer-element name="topeka-app" attributes="user categories" vertical layout>
    <template>
    
      <link rel="stylesheet" href="topeka-app.css.scss">
    
      <core-animated-pages selected="{{selected}}" transitions="cross-fade cross-fade-delayed scale-up slide-up slide-up-    offscreen slide-down tile-cascade hero-transition" flex auto on-core-animated-pages-transition-    end="{{transitionEndAction}}">    
    
        <div name="splash">
          <span fit class="splash {{ {wide: wide} | tokenList }}" cross-fade></span>
        </div>
    
        <topeka-categories id="categories" name="categories" user="{{user}}" allScores="{{allScores}}"
          categories="{{categories}}" category="{{category}}" wide="{{wide}}"
          on-core-activate="{{categorySelect}}"></topeka-categories>
    
        <topeka-category id="category" name="category" user="{{user}}" category="{{category}}" allScores="{{allScores}}"     wide="{{wide}}"></topeka-category>    
    
        <topeka-leaderboard name="leaderboard" user="{{user}}" wide="{{wide}}" disabled="{{disableLeaderboard}}"></topeka-    leaderboard>    
    
        <topeka-profile id="profile" name="profile" user="{{user}}" wide="{{wide}}"></topeka-profile>
      </core-animated-pages>
    
      <core-media-query query="min-width: {{responsiveWidth}}" queryMatches="{{wide}}"></core-media-query>
    
    </template>
    ...
    </polymer-element>
    

It should be rendered like this:

    ....
      <core-animated-pages selected="{{selected}}" transitions="cross-fade cross-fade-delayed scale-up slide-up slide-up-    offscreen slide-down tile-cascade hero-transition" flex auto on-core-animated-pages-transition-    end="{{transitionEndAction}}">    
    
        <div name="splash">
          ...
        </div>
    
        <topeka-categories id="categories" name="categories" user="{{user}}" allScores="{{allScores}}"
          categories="{{categories}}" category="{{category}}" wide="{{wide}}"
          on-core-activate="{{categorySelect}}"></topeka-categories>
    
        <topeka-category id="category" name="category" user="{{user}}" category="{{category}}" allScores="{{allScores}}"     wide="{{wide}}"></topeka-category>    
    
        <topeka-leaderboard name="leaderboard" user="{{user}}" wide="{{wide}}" disabled="{{disableLeaderboard}}"></topeka-    leaderboard>    
    
        <topeka-profile id="profile" name="profile" user="{{user}}" wide="{{wide}}"></topeka-profile>
      </core-animated-pages>

But it is rendered this way:

    ....
      <core-animated-pages selected="{{selected}}" transitions="cross-fade cross-fade-delayed scale-up slide-up slide-up-    offscreen slide-down tile-cascade hero-transition" flex auto on-core-animated-pages-transition-    end="{{transitionEndAction}}">    
    
        <div name="splash">
          ...
        </div>
    
        <topeka-categories id="categories" name="categories" user="{{user}}" allScores="{{allScores}}"
          categories="{{categories}}" category="{{category}}" wide="{{wide}}"
          on-core-activate="{{categorySelect}}">
             <topeka-category id="category" name="category" user="{{user}}" category="{{category}}" allScores="{{allScores}}"     wide="{{wide}}">
                   <topeka-leaderboard name="leaderboard" user="{{user}}" wide="{{wide}}" disabled="{{disableLeaderboard}}">
                        <topeka-profile id="profile" name="profile" user="{{user}}" wide="{{wide}}"></topeka-profile>
                   </topeka-    leaderboard>

             </topeka-category>

        </topeka-categories>

      </core-animated-pages>
    
It embeds the tags like if they were children but they aren't.

Strangely, if I surround each topeka-tag in a div, it doesn't replicate the problem, but the app will not work as it is not the markup needed.

Any tips about this?

**Comment by jdsampayo** [comment]
Tried using https://github.com/ahuth/emcee and it works as expected.

So, it must be a problem of polymer-rails.

**Comment by alchapone** [comment]
Fixed in [v0.2.6](https://github.com/alchapone/polymer-rails/releases/tag/v0.2.6)
