### ISSUE TITLE
Problem with duplicated polymer.js asset

### ISSUE THREAD

**Issue by gbisheimer** [alchapone/polymer-rails#37]
I'm developing an application using 3rd party polymer components that requires  `polymer` as dependency in the `bower.json` file. Executing `bower install` downloads the required dependencies and they take precedence over `polymer.js` library packaged in this gem and make things not work.

Deleting the duplicated files get things working again.

I would rather prefer to use the `bower` published package for polymer than the one included in this gem, so I know which version I'm using without having to look at the gem package.

**Comment by alchapone** [comment]
Not sure if this is still an issue

**Comment by caseybaggz** [comment]
@alchapone, as a front-end guy I agree with @gbisheimer. It would definitely be more profitable in the long run to keep Polymer up to date if you could change this gem to use Bower for installing Polymer and *all* the elements like they do in the [Polymer Starter Kit](https://developers.google.com/web/tools/polymer-starter-kit/). Then, all that would be left for the gem to do is handle all the imports like it is already doing.

You wouldn't have to have multiple gems then. You can just have one which installs Polymer, then give the optional `bower` commands for installing whatever element groups the user wants in the README?

Thoughts?

**Comment by alchapone** [comment]
I don't see any problems with using `bower` as package dependency manager, or even user `bower-rails`   that is meant to be used in rails apps. It is up to you if you want to install `polymer` and any other elements through bower.
