### ISSUE TITLE
`method_missing': undefined method `assets'

### ISSUE THREAD

**Issue by rami2929** [alchapone/polymer-rails#38]
Hi,

I'm new to Rails but I would love to use your polymer-rails for my project!

I included gem below:
gem 'polymer-rails'
gem 'polymer-core-rails'
gem 'polymer-paper-rails'

then did bundle install with success message. Now when I run: rails g polymer:install, I get:
.rvm/gems/ruby-1.9.3-p547/gems/railties-3.2.18/lib/rails/railtie/configuration.rb:85:in `method_missing': undefined method `assets' for #<Rails::Railtie::Configuration:0x007f85c5664e58> (NoMethodError)

Is there any way I can resolve this error message? (I'm using Rails 3.2.18. )

Your reply would be really appreciated.

Thank you

**Comment by alchapone** [comment]
@rami2929  Try using latest version 0.2.8 of polymer-rails. This should be fixed there

**Comment by alchapone** [comment]
@rami2929 any issues for version 0.2.8?
