### ISSUE TITLE
How to reference external CSS in Components 

### ISSUE THREAD

**Issue by alexvbush** [alchapone/polymer-rails#41]
Hey guys, love Polymer, love the gem, great work! 

I'm a bit confused on how to reference my Rails assets pipeline CSS in custom components.

I tried this:

`<%= stylesheet_link_tag 'application', media: 'all' %>`

inside of my `paper-submit-button.html.erb` component but I'm getting `no implicit conversion of nil into String` error in ` <%= html_import_tag 'application'%>`.

Maybe someone could give me a hint on how to do this?

Thanks.

**Comment by alexvbush** [comment]
Also, a side question - is it a good idea to have an `erb` pre-processor on my custom components? Seems like it worked but I'm not sure if there are going to be side effects down the road.

**Comment by alchapone** [comment]
1 - Just use `link` tag and specify css file you want to include. Same works with JS. But that is not really good idea to include `application.css` into your components because included css will be inlined into component itself. 
2 - You can use `.erb`, `.haml`, `.slim` or any other pre-processor
