### ISSUE TITLE
Update sprockets

### ISSUE THREAD

**Issue by piyushchauhan2011** [alchapone/polymer-rails#54]
Please update the sprockets to version 3.

**Comment by rafaelgonzalez** [comment]
I concur, can't use with brand new Rails 4.2.3 project.

**Comment by alchapone** [comment]
@rafaelgonzalez  Try v1.0.7

**Comment by rafaelgonzalez** [comment]
`1.0.7` also depends on `sprockets < 3.0.0`, so the issue still stands.

`bundle update` solves the issue with both `1.0.6` and `1.0.7` because it forces sprockets to be `< 3.0.0`. So I'll use `sprockets < 3.0.0` in the mean time!

**Comment by alchapone** [comment]
yeah.. there we a couple attempts to update sprockets processors to be 3.0.0 compliant in different forks. But no pull request so far. At some point I'll need to look into sprockets 3.0.0 docs and make needed changes.

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by bjarosze** [comment]
I've added support for sprockets v3. See pull request #56

**Comment by piyushchauhan2011** [comment]
I tried polymer-rails with `master` branch version, created a `hello` component but still the manifest file is showing blank. I included the component name correctly `//= require hello/hello`

![screen shot 2015-08-07 at 4 37 24 pm](https://cloud.githubusercontent.com/assets/693487/9130146/39b111da-3d23-11e5-81bc-73b27bd3c7e0.png)

**Comment by bjarosze** [comment]
Can you create simple project with example of this and put link to repository?

**Comment by piyushchauhan2011** [comment]
:+1: OK

**Comment by piyushchauhan2011** [comment]
https://github.com/piyushchauhan2011/polymer-rails-bug @bjarosze

**Comment by alchapone** [comment]
Hey @piyushchauhan2011 read polymer doc carefully ;) `hello` is not a valid name for polymer element. Try `hello-man` :smile:

**Comment by piyushchauhan2011** [comment]
Haha so silly of me @alchapone, I think then we can close this issue awesome work. I just checked works perfectly fine :+1:

**Comment by alchapone** [comment]
@piyushchauhan2011 Great! )
