### ISSUE TITLE
Using polymer and google-chart

### ISSUE THREAD

**Issue by alfredosegundo** [alchapone/polymer-rails#58]
Hi @alchapone.

I'm already using polymer in my rails 4 app and it's working very well, thank you for that.
But now I'm trying to add some google-chats and it looks like this gem doesn't support those.

If that is the case, do you have any suggestions?

Thank you.

**Comment by alchapone** [comment]
What do you mean by "gem doesn't support" ? How are you adding 'google-chats' to your project? and what result do you get?

**Comment by alchapone** [comment]
@alfredosegundo is this still and issue for you?
