### ISSUE TITLE
undefined method `context_class` with new versions of sass/sprockets

### ISSUE THREAD

**Issue by Frexuz** [alchapone/polymer-rails#60]
Error
```
/home/frexuz/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/polymer-rails-1.1.0/lib/polymer-rails/
railtie.rb:7:in `block in <class:Railtie>': undefined method `context_class' for nil:NilClass (NoMethodError)
```

Gemfile
```
source 'http://rubygems.org'
source 'http://gems.github.com/'

gem 'rails', '4.2.4'
gem 'polymer-rails'

#truncated...

group :assets do
  gem 'sass', '3.4.18'
  gem 'sass-rails', '~> 5.0.4'
  gem 'sprockets', '3.3.4'
  gem 'sprockets-rails', '3.0.0.beta2', :require => 'sprockets/railtie'
end
```

What's going on? :/

**Comment by alchapone** [comment]
For some reason `Rails.application.assets` is nil in your app. Can you investigate that?

**Comment by alchapone** [comment]
@Frexuz is this still an issue for you?

**Comment by Frexuz** [comment]
Sorry, I haven't been able to investigate further. I will let you know when I do :) @alchapone

**Comment by Frexuz** [comment]
Not sure how I'm supposed to debug further. I added `config.assets.enabled = true` in application.rb.

initializers/assets.rb
```
# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'
```

development.rb
```
Rails.application.configure do

  # Settings specified here will take precedence over those in config/application.rb

  # In the development environment your application's code is reloaded on
  # every request.  This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.cache_classes = false

  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = false

  # Show full error reports and disable caching
  config.consider_all_requests_local       = true
  config.action_controller.perform_caching = false

  #Cache testing
  config.action_controller.perform_caching = true
  # config.cache_store = :dalli_store, { :namespace => "episodecalendar", :expires_in => 7.day, :compress => true, :keepalive => true }

  # Don't care if the mailer can't send
  config.action_mailer.raise_delivery_errors = false

  # Print deprecation notices to the Rails logger
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Expands the lines which load the assets
  config.assets.debug = false

  # Mailer options
  config.action_mailer.default_url_options = { :host => "localhost" }

  # Sass
  # config.sass.cache = false

  # Adds additional error checking when serving assets at runtime.
  # Checks for improperly declared sprockets dependencies.
  # Raises helpful error messages.
  config.assets.raise_runtime_errors = true

  # Raises error for missing translations
  config.action_view.raise_on_missing_translations = true

  # Middlewares
  # config.middleware.insert_after ActionDispatch::Static, Rack::LiveReload

end
```

environment.rb
```
# Load the rails application
require File.expand_path('../application', __FILE__)

# Initialize the rails application
Rails.application.initialize!
```

application.rb
```
require File.expand_path('../boot', __FILE__)

require 'rails/all'
#require 'sprockets/railtie'
require 'csv'

Bundler.require(:default, Rails.env)

module Episodecalendar2
  class Application < Rails::Application

    # Custom directories with classes and modules you want to be autoloadable.
    config.autoload_paths += %W(#{Rails.root}/app/sweepers #{Rails.root}/lib)
    config.autoload_paths += Dir[ Rails.root.join('app', 'concerns', '**/') ]

    # Configure the default encoding used in templates for Ruby 1.9.
    config.encoding = "utf-8"

    # I18n
    config.i18n.available_locales = ['en', 'br', 'de', 'es', 'fr', 'it', 'pl', 'pt', 'tr']
    config.i18n.fallbacks = true
    config.i18n.fallbacks = { 'br': 'pt_BR' }

    # Configure sensitive parameters which will be filtered from the log file.
    config.filter_parameters += [:password]

    # Version of your assets, change this if you want to expire all your assets
    config.assets.version = '1.0'

    #Devise mailer layout
    config.to_prepare do
      Devise::Mailer.layout "email"
    end

    #Compass
    # config.compass.require "susy"
    config.assets.enabled = true

    config.active_record.raise_in_transactional_callbacks = true
  end
end
```

gemfile (removed anything not related to assets, and the gemfile.lock, and ran `bundle install` again)
```
source 'http://rubygems.org'
source 'http://gems.github.com/'

#Main
gem 'rails', '4.2.3'
gem 'therubyracer', require: 'v8'
gem 'jquery_mobile_rails'
gem 'polymer-rails'

group :assets do
  gem 'sass', '3.4.19'
  gem 'sass-rails', '5.0.4'
  gem 'sprockets', '3.4.0'
  gem 'sprockets-rails', '3.0.0.beta2', :require => 'sprockets/railtie'
  gem 'uglifier', '>= 1.3.0'
end
```

Have i missed something in the configurations?

**Comment by Frexuz** [comment]
Also just tried a completely new rails project (4.2.3)

ONLY thing I've changed is adding the gems to the Gemfile:

```
gem 'polymer-rails'

group :assets do
  gem 'sass', '3.4.19'
  gem 'sass-rails', '5.0.4'
  gem 'sprockets', '3.4.0'
  gem 'sprockets-rails', '3.0.0.beta2', :require => 'sprockets/railtie'
end
```

`rake assets:precompile RAILS_ENV="production"` runs fine without `polymer-rails`, as soon as I add it, I get the error.

**Comment by agnewtj** [comment]
Getting the same error.  The breakage seems to have been introduced with release 1.1.0.  If I downgrade to 1.0.8, it works.

**Comment by scarhand** [comment]
This seems to be related to sprockets-rails 3.x as well. After I downgraded sprockets-rails to v2.3.3 the assets compiled successfully. Upgrading sprockets-rails to v3 breaks the compilation of assets.

See also the comment at https://github.com/rails/sprockets-rails - config.assets.compile
"Enables Sprockets compile environment. If disabled, Rails.application.assets will be nil to prevent inadvertent compilation calls. View helpers will depend on assets being precompiled to public/assets in order to link to them. Initializers expecting Rails.application.assets during boot should be accessing the environment in a config.assets.configure block. See below."

**Comment by voondo** [comment]
Same error with sprockets-rails 3.x (works fine with 2.x)

**Comment by tden012** [comment]
I ran into the same issue - and after some searching, found a probable fix...

I'm kind of new to git, so I don't know how to do a pull request or what's involved - so I'll post what I've found here.

This is the link that gave me the idea for the solution:

https://github.com/reactjs/react-rails/commit/a3d0dad530ab4335ba0c66cf92d5d5ec6c007710

I believe that the problem may be solved if following code in /lib/polymer-rails/railtie.rb:

```ruby
initializer :polymer_html_import do
  helpers = %q{ include AssetTagHelper }
  ::ActionView::Base.module_eval(helpers)
  ::Rails.application.assets.context_class.class_eval(helpers)
end
```

is changed to this:

```ruby
initializer :polymer_html_import do |app|
  helpers = %q{ include AssetTagHelper }
  ::ActionView::Base.module_eval(helpers)
  app.config.assets.context_class.class_eval(helpers)
end
```

I'm not quite sure the mechanism that this works by - but it seems that other gem developers have gone down this path.

**Comment by TastyCatFood** [comment]
I got the same error.<br>
shifted ::Rails.application.assets.context_class.class_eval(helpers) to config.after_initialize.<br>
app.assets points to nil, so I tried:<br>
Sprockets.register_preprocessor 'text/html', Polymer::Rails::DirectiveProcessor<br>
Sprockets.register_bundle_processor 'text/html', ::Sprockets::Bundle<br>
Sprockets.register_postprocessor 'text/html', Polymer::Rails::ComponentsProcessorV3<br>
Now it runs but idk if it's working because I don't know how I'm supposed to populate components folder etc.

<code><pre>
module Polymer
  module Rails
    class Railtie < ::Rails::Railtie
      config.after_initialize do|app|
        app.assets.register_mime_type 'text/html', extensions: ['.html']
        helpers = %q{ include AssetTagHelper }
        ::ActionView::Base.module_eval(helpers)
        binding.pry
        ::Rails.application.assets.context_class.class_eval(helpers)
      end

      initializer :precompile_polymer do |app|
        if app.config.respond_to? (:assets)
          app.config.assets.precompile += %w( polymer/polymer.js )
        end
      end

      initializer :add_preprocessors do |app|
        if Polymer::Rails::LEGACY_SPROCKETS
          add_preprocessors_legacy(app)
        else
          add_preprocessors(app)
        end
      end

      private

      def add_preprocessors(app)
        binding.pry
        Sprockets.register_preprocessor 'text/html', Polymer::Rails::DirectiveProcessor
        Sprockets.register_bundle_processor 'text/html', ::Sprockets::Bundle
        Sprockets.register_postprocessor 'text/html', Polymer::Rails::ComponentsProcessorV3
      end

      def add_preprocessors_legacy(app)
        app.assets.register_mime_type "text/html", '.html'
        app.assets.register_preprocessor "text/html", Polymer::Rails::DirectiveProcessor
        app.assets.register_postprocessor 'text/html', :web do |context, data|
          Polymer::Rails::ComponentsProcessorV2.new(context, data).process
        end
      end

    end
  end
end
</code></pre>

**Comment by rafalee** [comment]
Having the same issue, I'm using

gem 'rails', '4.2.4'
gem 'polymer-rails', '1.2.2'

anyone figure it out a solution?

**Comment by hankish** [comment]
@rafalee: I'm running rails 4.2.5 and was getting this issue too.  When I updated my gemfile to:

```
gem 'rails', '4.2.5'
gem 'polymer-rails', '1.0.8'
```

and then ran a full `bundle update` it resolved the issue (and downgraded my sprockets gem version from 3.5.2 to 2.12.4).  if that doesn't work for you maybe add the line `gem 'sprockets', '2.12.4'`?

**Comment by LuisHCK** [comment]
@hankish I followed your instructions and works correctly! :+1:

**Comment by tostasqb** [comment]
Leaving my solution here. In the gem file I removed `sprockets` gem, leaving only `sprockets-rails` and with this order.

    gem 'sass-rails', '~> 5.0'
    gem 'sprockets-rails'

On `config/assets` updated context_class lines to

    config.assets.configure do |env|
      env.context_class.class_eval do
        # in my case I included....
        include Rails.application.routes.url_helpers
        include ActionView::Helpers
      end
    end

**Comment by Odaeus** [comment]
In case it's useful, I've implemented a fix that I'm still testing, but it works so far for me: https://github.com/Odaeus/polymer-rails/commit/dca1467475875d9418f618b6ebe20aec74737198
I just moved most of it to `config.after_initialize` because Sprockets isn't ready until then.

**Comment by alchapone** [comment]
@Frexuz Try using latest version of `polymer-rails`. It should now support sprockets v3.x

**Comment by hankish** [comment]
This issue has been completely resolved for me and I'm pretty sure it can be closed.
