### ISSUE TITLE
Paper elements are not displaying

### ISSUE THREAD

**Issue by alexvbush** [alchapone/polymer-rails#64]
Hey guys, I think I finally resolved installation issues but now paper elements just simply are not displaying on the page. Here's what I did:

1. add `gem 'polymer-elements-rails'` and `gem 'polymer-rails'` to my `Gemfile`
2. run `bundle exec rails g polymer:install`
3. insert `<%= html_import_tag 'application'%>` in application.html.erb layout.
4. add `//= require paper-fab/paper-fab`, `//= require iron-icons/iron-icons`, and `//= require paper-button/paper-button`

Then I tried to use `<paper-button>this is a button</<paper-button>>` or `<paper-fab icon="add"></paper-fab>` in my views but they don't seem to be rendering properly. I get them render like that on the page:
```html
<paper-fab icon="add" role="button" tabindex="0" aria-disabled="false" class="x-scope paper-fab-0"></paper-fab>
<paper-fab mini="" icon="favorite" role="button" tabindex="0" aria-disabled="false" class="x-scope paper-fab-0"></paper-fab>
<paper-fab src="star.png" role="button" tabindex="0" aria-disabled="false" class="x-scope paper-fab-0"></paper-fab>
```
but I don't think this is the way they suppose to render. As far as I understand polymer should create some shadow dom representation of those tags. What am I doing wrong?

**Comment by alexvbush** [comment]
@alchapone would appreciate your help. thx.

**Comment by alexvbush** [comment]
I also tried to create my own polymer component and it seems like it's not getting rendered. I think, even though my rails layout loads all the html imports, Polymer just doesn't pick up on those custom tags (either my own or paper).

**Comment by JonasSynergium** [comment]
@alexvbush which version of nokogumbo your project is using? It looks like nokogumbo 1.4.3 deletes template tags from polymer components. I don't get this issue with nokogumbo 1.4.2 or lower.

**Comment by nanowang** [comment]
@JonasSynergium 

Thanks! I've been debugging the missing template for a whole day...

**Comment by nanowang** [comment]
@JonasSynergium Tons of thanks!

I've been debugging this missing template thing for a whole day.

BTW, so is this a bug of nokogumbo?

**Comment by jpegjames** [comment]
@nanowang did changing nokogumbo from 1.4.3 to 1.4.2 work for you? It did not seem to resolve my problem.

If I disable the 'polymer-rails' gem and manually link the files, it works:

````html
<script src="/assets/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="/assets/paper-button/paper-button.html">
...
````

…but I lose the convenience of the application.html manifest file.

**Comment by nanowang** [comment]
@jpegjames 

Forcing to depend on the 1.4.2 works for me.

**Comment by tikitikifoofoo** [comment]
I can't get any elements to render using the latest version (1.0.0). None of the above solutions have worked for me.

**Comment by ryangoh** [comment]
When try to view /assets/paper-button/paper-button.html
The template tag, style tag is missing, I think that cause the issue

**Comment by alchapone** [comment]
Checked with recent version of gem (1.2.2), paper elements working fine with rails 4.2.4. Anyone has any problems on recent version?

**Comment by nanowang** [comment]
The current version is file yet we still don't know the real reason behind the issue.

**Comment by alexvbush** [comment]
ok, I just tested it and can confirm that using a combination of `Rails 4.2.4`, `polymer-rails ~> 1.2.2`, and `polymer-elements-rails 1.0.1` it does work and get to have a `paper-button` display.

**Comment by alexvbush** [comment]
Will close the issue for now.

**Comment by JustLey** [comment]
I guess this is happening again in Rails 5.
Tested with 2 config:

Rails 5.0.0
Polymer-rails 1.2.4.1
Nokogumbo 1.4.2 / everything above with Nokogumbo 1.4.7 too

Tried to use polymer-rails 1.2.2 too, no luck. I was comparing with another implementation of the same code (the code from polymail, source: https://github.com/ebidel/polymer-gmail/blob/master/index.html and production: https://poly-mail.appspot.com/?debug) and #shadow-root (open) that should appear under some tags in the inspect tab from Chrome just doesn't.
